### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by jayrav13** [kellyjandrews/php-laravel-todoapp#1]
For:

https://github.com/kellyjandrews/php-laravel-todoapp/blob/master/routes/api.php#L5

Check out these two methods for organizing routing, I'm a huge fan of the first one:

1) https://laravel.com/docs/5.4/routing#route-groups

```php
Route::group(['prefix' => 'todos'], function() {

    Route::get('/', "TodosController@index");
    Route::post('/', "TodosController@create");

    Route::group(['prefix' => '{todo_id}'], function() {
        Route::get('/', "TodosController@get");
        Route::patch('/', "TodosController@update");
        Route::delete('/', "TodosController@delete");
    });

});
```

2) https://laravel.com/docs/5.4/controllers#resource-controllers

Predefined resource controllers

**Comment by kellyjandrews** [comment]
Yeah - I like it!  What I will do is the second group using `['prefix' => '{todo_id}']` because the todobackend.com spec uses the root url as it's basis, and not `/todos` like normal APIs - which is unfortunate.
